/* eslint-disable */
export enum MemberEventsEnum {
    MEMBER_CREATED = 'MEMBER_CREATED',
    MEMBER_UPDATED = 'MEMBER_UPDATED',
    MEMBER_DELETED = 'MEMBER_DELETED',
    MEMBER_DEACTIVATED = 'MEMBER_DEACTIVATED',
    MEMBER_ACTIVATED = 'MEMBER_ACTIVATED',
    MEMBER_DELETED_PERMANENTLY = 'MEMBER_DELETED_PERMANENTLY',
    MEMBER_REACTIVATED = 'MEMBER_REACTIVATED',
}