/* eslint-disable prettier/prettier */

/**
 *
 *This is Just a simple interface of items to be stored in any collection in the database
 * Any record you store in any collection in your database MUST extend this interface 
 * All this is automatically generated by the API but you can set your own values as you like
 * Anything with a question mark is optional and automatically managed by the API
 */
export interface RecordInterface {
  id: string,

  /**
   * Just an id of who created the record, to ensure only authorized users or apps can make any change of any kind to the database
   */
  createdBy: string,
  createdAt?: string,

  // Update
  updatedAt?: string,
  updatedBy?: string,

  // images
  imageURLs?: string[],
  documentURLs?: string[],

  // Delete
  deleted?: boolean;
  deletedBy?: string;

  status?: string,
  serialNumber?: string,
  day?: string,
}
